#!/usr/bin/env python
#
# Copyright 2012 Dominic Rout
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
  Provides full, three-legged authentication with Twitter using CherryPy to generate the needed keys.
  
  Your browser should open to a local URL to begin the process.

  Tokens will be automatically saved in the format accepted by this library (YAML).
"""

import cherrypy, webbrowser, sys, yaml, os, shutil

from twitterwrapper import access_tokens
from twitterwrapper._utils import copy_default

CONFIG_FILE = "consumer.yaml"

class AuthenticateTwitterCherryPy(access_tokens.AuthenticationProcess):
  def __init__(self, config):
    access_tokens.AuthenticationProcess.__init__(self, config)

  def generate(self):    
      raise cherrypy.HTTPRedirect(self.generate_authorize_url("http://localhost:8080/callback"))

  generate.exposed = True

  def callback(self, oauth_verifier, oauth_token):    
    token = self.verify_authorization(oauth_verifier)

    yield "Access Token: <br />\n"

    yield "    - oauth_consumer_token        = %s  <br />\n" % self.oauth_consumer_token
    yield "    - oauth_consumer_secret = %s <br />\n" % self.oauth_consumer_secret


    yield "    - oauth_token        = %s <br />\n" % token['access_token_key']
    yield "    - oauth_token_secret = %s <br />\n" % token['access_token_secret']
    yield "The tokens above have been saved to access_tokens.yaml <br />" 
    yield "Use C-c on the terminal to end this process." 

    self.token_store.add_auth(**token)
    self.token_store.save()

  callback.exposed = True


if __name__ == "__main__": 
  try:
    with open(CONFIG_FILE) as f:
      config = yaml.load(f)
    cherrypy.tree.mount(AuthenticateTwitterCherryPy(config["oauth"]))
    cherrypy.server.socket_port = 8080
    cherrypy.engine.start()
    webbrowser.open("http://localhost:8080/generate")
    cherrypy.engine.block()

  except IOError:
    print "Creating configuration files:"

    #try: 
    copy_default(CONFIG_FILE)
    print "Created %s" % CONFIG_FILE

    copy_default(access_tokens.DEFAULT_ACCESS_TOKENS_FILE)
    print "Created %s" % access_tokens.DEFAULT_ACCESS_TOKENS_FILE
    # except IOError:
    #   raise IOError("Unable to copy file from package. Giving up.")
    
    print "Please update %s to include your Twitter API consumer token and run again." % CONFIG_FILE

    sys.exit()

